// Generated by gencpp from file agitr/Num.msg
// DO NOT EDIT!


#ifndef AGITR_MESSAGE_NUM_H
#define AGITR_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agitr
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num1(0)
    , num2(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
    }



   typedef int64_t _num1_type;
  _num1_type num1;

   typedef uint8_t _num2_type;
  _num2_type num2;




  typedef boost::shared_ptr< ::agitr::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agitr::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::agitr::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::agitr::Num > NumPtr;
typedef boost::shared_ptr< ::agitr::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agitr::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agitr::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agitr

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'agitr': ['/home/fpereira/catkin_ws/src/agitr/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agitr::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agitr::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agitr::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agitr::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agitr::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agitr::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agitr::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b574688662d0f05e2a80afca86bae2f0";
  }

  static const char* value(const ::agitr::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb574688662d0f05eULL;
  static const uint64_t static_value2 = 0x2a80afca86bae2f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::agitr::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agitr/Num";
  }

  static const char* value(const ::agitr::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agitr::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num1\n\
uint8 num2\n\
";
  }

  static const char* value(const ::agitr::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agitr::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agitr::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agitr::Num_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGITR_MESSAGE_NUM_H
