// Generated by gencpp from file group_hw1/move_robot.msg
// DO NOT EDIT!


#ifndef GROUP_HW1_MESSAGE_MOVE_ROBOT_H
#define GROUP_HW1_MESSAGE_MOVE_ROBOT_H

#include <ros/service_traits.h>


#include <group_hw1/move_robotRequest.h>
#include <group_hw1/move_robotResponse.h>


namespace group_hw1
{

struct move_robot
{

typedef move_robotRequest Request;
typedef move_robotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_robot
} // namespace group_hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::group_hw1::move_robot > {
  static const char* value()
  {
    return "ae646fe5fb39d5a27e6b0cd44ed9a25e";
  }

  static const char* value(const ::group_hw1::move_robot&) { return value(); }
};

template<>
struct DataType< ::group_hw1::move_robot > {
  static const char* value()
  {
    return "group_hw1/move_robot";
  }

  static const char* value(const ::group_hw1::move_robot&) { return value(); }
};


// service_traits::MD5Sum< ::group_hw1::move_robotRequest> should match 
// service_traits::MD5Sum< ::group_hw1::move_robot > 
template<>
struct MD5Sum< ::group_hw1::move_robotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::group_hw1::move_robot >::value();
  }
  static const char* value(const ::group_hw1::move_robotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_hw1::move_robotRequest> should match 
// service_traits::DataType< ::group_hw1::move_robot > 
template<>
struct DataType< ::group_hw1::move_robotRequest>
{
  static const char* value()
  {
    return DataType< ::group_hw1::move_robot >::value();
  }
  static const char* value(const ::group_hw1::move_robotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::group_hw1::move_robotResponse> should match 
// service_traits::MD5Sum< ::group_hw1::move_robot > 
template<>
struct MD5Sum< ::group_hw1::move_robotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::group_hw1::move_robot >::value();
  }
  static const char* value(const ::group_hw1::move_robotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::group_hw1::move_robotResponse> should match 
// service_traits::DataType< ::group_hw1::move_robot > 
template<>
struct DataType< ::group_hw1::move_robotResponse>
{
  static const char* value()
  {
    return DataType< ::group_hw1::move_robot >::value();
  }
  static const char* value(const ::group_hw1::move_robotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUP_HW1_MESSAGE_MOVE_ROBOT_H
