// Generated by gencpp from file group_hw1/move_robotResponse.msg
// DO NOT EDIT!


#ifndef GROUP_HW1_MESSAGE_MOVE_ROBOTRESPONSE_H
#define GROUP_HW1_MESSAGE_MOVE_ROBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace group_hw1
{
template <class ContainerAllocator>
struct move_robotResponse_
{
  typedef move_robotResponse_<ContainerAllocator> Type;

  move_robotResponse_()
    : valid_action(false)  {
    }
  move_robotResponse_(const ContainerAllocator& _alloc)
    : valid_action(false)  {
    }



   typedef uint8_t _valid_action_type;
  _valid_action_type valid_action;




  typedef boost::shared_ptr< ::group_hw1::move_robotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::group_hw1::move_robotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct move_robotResponse_

typedef ::group_hw1::move_robotResponse_<std::allocator<void> > move_robotResponse;

typedef boost::shared_ptr< ::group_hw1::move_robotResponse > move_robotResponsePtr;
typedef boost::shared_ptr< ::group_hw1::move_robotResponse const> move_robotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::group_hw1::move_robotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::group_hw1::move_robotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace group_hw1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'group_hw1': ['/home/fpereira/catkin_ws/src/group_hw1/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::group_hw1::move_robotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::group_hw1::move_robotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::group_hw1::move_robotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::group_hw1::move_robotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::group_hw1::move_robotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::group_hw1::move_robotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::group_hw1::move_robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b900a0099621387ec000978e7bf9f1b2";
  }

  static const char* value(const ::group_hw1::move_robotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb900a0099621387eULL;
  static const uint64_t static_value2 = 0xc000978e7bf9f1b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::group_hw1::move_robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "group_hw1/move_robotResponse";
  }

  static const char* value(const ::group_hw1::move_robotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::group_hw1::move_robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool valid_action\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::group_hw1::move_robotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::group_hw1::move_robotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.valid_action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct move_robotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::group_hw1::move_robotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::group_hw1::move_robotResponse_<ContainerAllocator>& v)
  {
    s << indent << "valid_action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid_action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUP_HW1_MESSAGE_MOVE_ROBOTRESPONSE_H
