// Generated by gencpp from file group_hw1/move_robotRequest.msg
// DO NOT EDIT!


#ifndef GROUP_HW1_MESSAGE_MOVE_ROBOTREQUEST_H
#define GROUP_HW1_MESSAGE_MOVE_ROBOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace group_hw1
{
template <class ContainerAllocator>
struct move_robotRequest_
{
  typedef move_robotRequest_<ContainerAllocator> Type;

  move_robotRequest_()
    : command(0)
    , target(0)  {
    }
  move_robotRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , target(0)  {
    }



   typedef int64_t _command_type;
  _command_type command;

   typedef int64_t _target_type;
  _target_type target;




  typedef boost::shared_ptr< ::group_hw1::move_robotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::group_hw1::move_robotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct move_robotRequest_

typedef ::group_hw1::move_robotRequest_<std::allocator<void> > move_robotRequest;

typedef boost::shared_ptr< ::group_hw1::move_robotRequest > move_robotRequestPtr;
typedef boost::shared_ptr< ::group_hw1::move_robotRequest const> move_robotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::group_hw1::move_robotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::group_hw1::move_robotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace group_hw1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'group_hw1': ['/home/fpereira/catkin_ws/src/group_hw1/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::group_hw1::move_robotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::group_hw1::move_robotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::group_hw1::move_robotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::group_hw1::move_robotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::group_hw1::move_robotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::group_hw1::move_robotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::group_hw1::move_robotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d3a610548424ae98412e86c05a4c2e5";
  }

  static const char* value(const ::group_hw1::move_robotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d3a610548424ae9ULL;
  static const uint64_t static_value2 = 0x8412e86c05a4c2e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::group_hw1::move_robotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "group_hw1/move_robotRequest";
  }

  static const char* value(const ::group_hw1::move_robotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::group_hw1::move_robotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 command\n\
int64 target\n\
";
  }

  static const char* value(const ::group_hw1::move_robotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::group_hw1::move_robotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct move_robotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::group_hw1::move_robotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::group_hw1::move_robotRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int64_t>::stream(s, indent + "  ", v.command);
    s << indent << "target: ";
    Printer<int64_t>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUP_HW1_MESSAGE_MOVE_ROBOTREQUEST_H
